# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: 'root'
  password: 'root'
  database: flash_photograph
  host: localhost

production:
  <<: *default
  username: 'root'
  password: <%= ENV["FLASH_PHOTOGRAPH_DB_PASS"] %>
  database: flash_photograph
  host: localhost